version: "3.8"
services:
  web:
    build: .
    ports:
      - "8000:8000"
    command: >
      bash -c "ls -l
      && poetry run python manage.py runserver 0.0.0.0:8000"
    volumes: # automatically syncs docker fs with local fs
      - .:/code
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

volumes:
  postgres_data: