version: "3.8"
services:
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  web:
    build: .
    command: sh /app/start.sh
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data: